### ISSUE TITLE
1.4.11 throwing errors as Core has updated and now not supported

### ISSUE THREAD

**Issue by ghost00-Ricgames** [sw5e-foundry/token-action-hud-sw5e#5]
The current build is now out of sync with the current Token Action HUD core 1.5.0.

System throw error about compatibility, and is non functional without rolling back to previous Core. 
![Screenshot 2023-10-30 075230](https://github.com/sw5e-foundry/token-action-hud-sw5e/assets/122754683/9dd0a93f-35b5-4597-ae5a-081699ea4435)

**Comment by itsmeitmohthy** [comment]
getting the same error as well!
